apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      type: cache-service
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis
        type: cache-service
    spec:
      containers:
        - name: redis-contaier
          image: redis:alpine