apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    app: redis
    type: cache-service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
