apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
      type: front-end
  template:
    metadata:
      name: result-app-pod
      labels:
        app: result-app
        type: front-end
    spec:
      containers:
        - name: result-app-container
          image: result-app
          imagePullPolicy: Never
          ports:
          - containerPort: 3000