apiVersion: v1
kind: Pod
metadata:
  name: vote-app-pod
  labels:
    name: vote-app
    type: front-end
spec:
  containers:
    - name: vote-app-container
      image: vote-app
      imagePullPolicy: Never
