apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-Deployment
  labels:
    name: vote-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
      type: front-end
  template:
    metadata:
      name: vote-app-pod
      labels:
        app: vote-app
        type: front-end
    spec:
      containers:
        - name: vote-app-container
          image: vote-app
          imagePullPolicy: Never
          ports:
          - containerPort: 3001