apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app
    type: back-end
spec:
  containers:
    - name: worker-app-ontainer
      image: worker-app
      imagePullPolicy: Never

